services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      USERNAME: "user"
      PASSWORD: "pass"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3390:3389/tcp
      - 3390:3389/udp
      - 4902:4902
    volumes:
      - ./windows:/storage
      - ./source/oem:/oem
      - ./:/shared
    restart: always
    stop_grace_period: 2m




# sudo docker-compose down
# sudo rm -R windows
# sudo docker-compose up -d
